# Generated by Django 5.1.1 on 2025-07-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_appointment_doctor_alter_appointment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_types',
            field=models.ManyToManyField(related_name='doctors', to='booking.appointmenttype'),
        ),
    ]
